In [54]:
import numpy as np

data=np.load('data.npy')
target=np.load('target.npy')

In [55]:
from sklearn.svm import SVC #importing the SVM
from sklearn.decomposition import PCA #importing PCA
from sklearn.pipeline import make_pipeline

pca=PCA(n_components=150,whiten=True,random_state=42)
svc=SVC(kernel='rbf')

model=make_pipeline(pca,svc)

In [56]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [57]:
model.fit(train_data,train_target)

D:\Programs\Anaconda\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Pipeline(memory=None,
     steps=[('pca', PCA(copy=True, iterated_power='auto', n_components=150, random_state=42,
  svd_solver='auto', tol=0.0, whiten=True)), ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False))])

In [58]:
predicted_target=model.predict(test_data)

In [59]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(test_target,predicted_target)
print(acc)

1.0


In [61]:
from sklearn.metrics import classification_report

print(classification_report(test_target,predicted_target,target_names=['Barack Obama', 'Donald Trump', 'George W Bush']))

               precision    recall  f1-score   support

 Barack Obama       1.00      1.00      1.00        11
 Donald Trump       1.00      1.00      1.00         9
George W Bush       1.00      1.00      1.00         9

    micro avg       1.00      1.00      1.00        29
    macro avg       1.00      1.00      1.00        29
 weighted avg       1.00      1.00      1.00        29



In [62]:
from sklearn.metrics import confusion_matrix

matrix=confusion_matrix(test_target,predicted_target)
print(matrix)

[[11  0  0]
 [ 0  9  0]
 [ 0  0  9]]


In [63]:
import joblib

joblib.dump(model,'SVM-Face Recognition.sav')

['SVM-Face Recognition.sav']

In [64]:
np.max(train_data[1])

250